version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: iot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: iot-backend
    restart: always
    ports:
      - "4007:4007"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/iotdb
      - PORT=4007
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend2
    container_name: iot-frontend
    restart: always
    ports:
      - "3007:3000"
    env_file:
      - ./frontend2/.env.local
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4007
      - NEXT_PUBLIC_SOCKET_URL=ws://localhost:4007
    volumes:
      - ./frontend2:/app
      - /app/node_modules

volumes:
  mongo-data:
